server:
  port: 80
logging:
  level:
    root: info
    web: info

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: digibank
          uri: lb://digibank
          predicates:
            - Path=/digibank/**
          filters:
            - RewritePath=/digibank/(?<path>.*), /$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      default-filters:
        - TokenRelay
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/auth/realms/demo-realm
            # Individual properties can also be provided this way
        #            token-uri: http://localhost:8085/auth/realms/amrutrealm/protocol/openid-connect/token
        #            authorization-uri: http://localhost:8085/auth/realms/amrutrealm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8085/auth/realms/demo-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:8085/auth/realms/demo-realm/protocol/openid-connect/certs
        registration:
          keycloak:
            provider: keycloak
            scope: openid
            client-id: test
            client-secret: ZKjeJVGV0qK7okiK1cBX22uPIAMo4kVw
            authorization-grant-type: bearer
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  sec:
    config:
      allowedOrigins: http://localhost:4200
#  main:
#    web-application-type: reactive
#
#  securityConstraints:
#    authRoles:
#keycloak:
#  realm: demo-realm
#  auth-server-url: http://localhost:8085/auth
#  ssl-required: external
#  resource: test
#  use-resource-role-mappings: false
#  bearer-only: false
#  credentials:
#    secret: ZKjeJVGV0qK7okiK1cBX22uPIAMo4kVw