server:
  port: 81
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info
    web: info

spring:
  application:
    name: digibank
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"

  sec:
    config:
      allowedOrigins: http://localhost:4200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/demo-realm
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=digibank;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2016Dialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html