server:
  port: 81
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info
    web: info

spring:
  application:
    name: digibank
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"


  sec:
    config:
      allowedOrigins: http://localhost:4200

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html